<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="admin-PC" failures="0" tests="2" name="com.fa.shipment.VerifyCreateShipment" time="23.267" errors="2" timestamp="2021-03-06T21:00:46 IST" skipped="0">
  <testcase classname="com.fa.shipment.VerifyCreateShipment" name="test" time="0.037">
    <error message="
[public void com.fa.shipment.VerifyCreateShipment.test(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Exception] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: test([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=6, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) 1,(java.lang.String) CreateShipment]" type="org.testng.internal.reflect.MethodMatcherException">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void com.fa.shipment.VerifyCreateShipment.test(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Exception] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: test([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=6, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) 1,(java.lang.String) CreateShipment]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:905)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="com.fa.shipment.VerifyCreateShipment" name="checkTestuiteExicution" time="23.230">
    <error message="java.io.IOException: Failed to delete original file &#039;C:\Users\ADMINI~1.ADM\AppData\Local\Temp\7037852688820723546\chromedriver.exe&#039; after copy to &#039;C:\Users\Administrator.admin-PC\.cache\selenium\chromedriver\win32\89.0.4389.23\chromedriver.exe&#039;" type="io.github.bonigarcia.wdm.config.WebDriverManagerException">
      <![CDATA[io.github.bonigarcia.wdm.config.WebDriverManagerException: java.io.IOException: Failed to delete original file 'C:\Users\ADMINI~1.ADM\AppData\Local\Temp\7037852688820723546\chromedriver.exe' after copy to 'C:\Users\Administrator.admin-PC\.cache\selenium\chromedriver\win32\89.0.4389.23\chromedriver.exe'
at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:777)
at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:574)
at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:793)
at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:774)
at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:574)
at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:767)
at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:574)
at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:288)
at com.main.BaseInIt.startUP(BaseInIt.java:96)
at com.fa.shipment.VerifyShipment.checkTestuiteExicution(VerifyShipment.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:327)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.io.IOException: Failed to delete original file 'C:\Users\ADMINI~1.ADM\AppData\Local\Temp\7037852688820723546\chromedriver.exe' after copy to 'C:\Users\Administrator.admin-PC\.cache\selenium\chromedriver\win32\89.0.4389.23\chromedriver.exe'
at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2276)
at org.apache.commons.io.FileUtils.moveFileToDirectory(FileUtils.java:2310)
at io.github.bonigarcia.wdm.online.Downloader.downloadAndExtract(Downloader.java:147)
at io.github.bonigarcia.wdm.online.Downloader.download(Downloader.java:90)
at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:653)
at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:568)
... 27 more
]]>
    </error>
  </testcase> <!-- checkTestuiteExicution -->
  <system-out/>
</testsuite> <!-- com.fa.shipment.VerifyCreateShipment -->
